# NumPy 

(pronounced (NUM-py)) is a library for the Python programming language, adding support for large, multi-dimensional arrays and matrices, along with a large collection of high-level mathematical functions to operate on these arrays.

The NumPy library is the core library for scientific computing in Python. It provides a high-performance multidimensional array object, and tools for working with these arrays. 

https://s3.amazonaws.com/assets.datacamp.com/blog_assets/Numpy_Python_Cheat_Sheet.pdf

In [227]:
import numpy as np

## 1d Array

In [114]:
a = np.array([1,2,3])
a.ndim

1

## 2d Array

In [15]:
b = np.array([(1,2,3), (4,5,6)])
b.ndim

2

## 3d Array

In [159]:
c = np.array([[(1,2,3)], [(4,5,6)], [(7,8,9)]])
print(c.ndim)
c

3


array([[[1, 2, 3]],

       [[4, 5, 6]],

       [[7, 8, 9]]])

## Create a 2d array of zeros

In [23]:
zeros = np.zeros((3,3))
print(zeros.ndim)
zeros

2


array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

## Create a 3d array of zeros

In [24]:
zeros = np.zeros((3,3,3))
print(zeros.ndim)
zeros

3


array([[[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]]])

## Evenly spaced values

In [33]:
bytwos = np.arange(10,50,2)
print(bytwos.ndim)
bytwos

1


array([10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40, 42,
       44, 46, 48])

## Constant array 

In [39]:
threes = np.full((5,5),3) 
threes

array([[3, 3, 3, 3, 3],
       [3, 3, 3, 3, 3],
       [3, 3, 3, 3, 3],
       [3, 3, 3, 3, 3],
       [3, 3, 3, 3, 3]])

## Identity matrix

In [45]:
idMatrix = np.eye(6) 
idMatrix

array([[1., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 1.]])

## Ranmdom value matrix 

In [149]:
rando = np.random.random((3,3)) 
rando

array([[0.59447703, 0.86268204, 0.19779586],
       [0.009365  , 0.9088827 , 0.52862459],
       [0.41052192, 0.34998317, 0.17411359]])

In [145]:
empty =  np.empty((3,3)) 
print(empty)

print("    ")
empty[0,0] = 9 
print(empty)




[[0.49287987 0.65539916 0.48145509]
 [0.05414735 0.21373529 0.07190865]
 [0.55189979 0.63740314 0.39517973]]
    
[[9.         0.65539916 0.48145509]
 [0.05414735 0.21373529 0.07190865]
 [0.55189979 0.63740314 0.39517973]]


## Shape

In [77]:
rando.shape

(3, 3)

## Length 

In [78]:
len(rando)

3

## Number of dims

In [80]:
c.ndim

3

## Size of object

In [81]:
b.size

6

## Data Type of object

In [88]:
print(c.dtype)
#not to be confused with python type
type(c)

int64


numpy.ndarray

## Compare

In [95]:
a = 1

b = 2 

a == b

False

In [102]:
f = np.array([(1,2,3), (4,5,6)])
g = np.array([(2,2,3), (4,5,7)])
print(f.ndim)

2


In [103]:
f == g

array([[False,  True,  True],
       [ True,  True, False]])

In [104]:
f < g

array([[ True, False, False],
       [False, False,  True]])

## Aggregates

In [106]:
f.sum()

21

In [107]:
g.min()

2

In [118]:
#Maximum value of an array row
rando.max(axis=0)

array([0.51885162, 0.47112319, 0.91917837])

In [126]:
a.mean()

2.0

In [130]:
np.median(rando)

0.471123186032542

In [153]:
rando[0,0] = 9
rando[0,1] = 8
rando[0,2] = 7

print(rando)

rando.sort()

print(rando)

[[9.         8.         7.        ]
 [0.009365   0.52862459 0.9088827 ]
 [0.17411359 0.34998317 0.41052192]]
[[7.         8.         9.        ]
 [0.009365   0.52862459 0.9088827 ]
 [0.17411359 0.34998317 0.41052192]]


## Subsetting 

In [163]:
a = np.array([1,2,3])
print(a.ndim)
a


1


array([1, 2, 3])

In [164]:
a[0]

1

In [165]:
a[2]

3

In [170]:
b = np.array([(1,2,3), (4,5,6)])
print(b.ndim)
print(b)

2
[[1 2 3]
 [4 5 6]]


In [171]:
#[row,column]
b[0,0]

1

In [172]:
b[0,1]

2

In [173]:
b[0,2]

3

In [174]:
b[1,2]

6

In [191]:
c = np.array([[[10, 11, 12], [13, 14, 15], [16, 17, 18]],
               [[20, 21, 22], [23, 24, 25], [26, 27, 28]],
               [[30, 31, 32], [33, 34, 35], [36, 37, 38]]])
print(c.ndim)
c

3


array([[[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]],

       [[20, 21, 22],
        [23, 24, 25],
        [26, 27, 28]],

       [[30, 31, 32],
        [33, 34, 35],
        [36, 37, 38]]])

In [220]:
#c[ dim, row, col ]
c[0]

array([[10, 11, 12],
       [13, 14, 15],
       [16, 17, 18]])

In [221]:
#c[ dim, row, col ]
c[2,2,2]

38

In [223]:
#c[ dim, row, col ]
c[0,0,:3]

array([10, 11, 12])

In [224]:
#c[ dim, row, col ]
c[0,1,:2]

array([13, 14])

In [226]:
#c[ dim, row, col ]
c[1,:,:]

array([[20, 21, 22],
       [23, 24, 25],
       [26, 27, 28]])