# NumPy 

(pronounced (NUM-py)) is a library for the Python programming language, adding support for large, multi-dimensional arrays and matrices, along with a large collection of high-level mathematical functions to operate on these arrays.

The NumPy library is the core library for scientific computing in Python. It provides a high-performance multidimensional array object, and tools for working with these arrays. 

https://s3.amazonaws.com/assets.datacamp.com/blog_assets/Numpy_Python_Cheat_Sheet.pdf

In [1]:
import numpy as np

## 1d Array

In [2]:
a = np.array([1,2,3])
a.ndim

1

## 2d Array

In [3]:
b = np.array([(1,2,3), (4,5,6)])
b.ndim

2

## 3d Array

In [4]:
c = np.array([[(1,2,3)], [(4,5,6)], [(7,8,9)]])
print(c.ndim)
c

3


array([[[1, 2, 3]],

       [[4, 5, 6]],

       [[7, 8, 9]]])

## Create a 2d array of zeros

In [5]:
zeros = np.zeros((3,3))
print(zeros.ndim)
zeros

2


array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

## Create a 3d array of zeros

In [6]:
zeros = np.zeros((3,3,3))
print(zeros.ndim)
zeros

3


array([[[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]]])

## Evenly spaced values

In [7]:
bytwos = np.arange(10,50,2)
print(bytwos.ndim)
bytwos

1


array([10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40, 42,
       44, 46, 48])

## Constant array 

In [8]:
threes = np.full((5,5),3) 
threes

array([[3, 3, 3, 3, 3],
       [3, 3, 3, 3, 3],
       [3, 3, 3, 3, 3],
       [3, 3, 3, 3, 3],
       [3, 3, 3, 3, 3]])

## Identity matrix

In [9]:
idMatrix = np.eye(6) 
idMatrix

array([[1., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 1.]])

## Ranmdom value matrix 

In [10]:
rando = np.random.random((3,3)) 
rando

array([[0.8019063 , 0.37587885, 0.74405353],
       [0.33748669, 0.90127236, 0.27954017],
       [0.10542404, 0.790967  , 0.46290504]])

In [11]:
empty =  np.empty((3,3)) 
print(empty)

print("    ")
empty[0,0] = 9 
print(empty)




[[0.8019063  0.37587885 0.74405353]
 [0.33748669 0.90127236 0.27954017]
 [0.10542404 0.790967   0.46290504]]
    
[[9.         0.37587885 0.74405353]
 [0.33748669 0.90127236 0.27954017]
 [0.10542404 0.790967   0.46290504]]


## Shape

In [12]:
rando.shape

(3, 3)

## Length 

In [13]:
len(rando)

3

## Number of dims

In [14]:
c.ndim

3

## Size of object

In [15]:
b.size

6

## Data Type of object

In [16]:
print(c.dtype)
#not to be confused with python type
type(c)

int64


numpy.ndarray

## Compare

In [17]:
a = 1

b = 2 

a == b

False

In [18]:
f = np.array([(1,2,3), (4,5,6)])
g = np.array([(2,2,3), (4,5,7)])
print(f.ndim)

2


In [19]:
f == g

array([[False,  True,  True],
       [ True,  True, False]])

In [20]:
f < g

array([[ True, False, False],
       [False, False,  True]])

## Aggregates

In [21]:
f.sum()

21

In [22]:
g.min()

2

In [23]:
#Maximum value of an array row
rando.max(axis=0)

array([0.8019063 , 0.90127236, 0.74405353])

In [24]:
np.median(rando)

0.4629050384646719

In [25]:
rando[0,0] = 9
rando[0,1] = 8
rando[0,2] = 7

print(rando)

rando.sort()

print(rando)

[[9.         8.         7.        ]
 [0.33748669 0.90127236 0.27954017]
 [0.10542404 0.790967   0.46290504]]
[[7.         8.         9.        ]
 [0.27954017 0.33748669 0.90127236]
 [0.10542404 0.46290504 0.790967  ]]


## Subsetting 

In [26]:
a = np.array([1,2,3])
print(a.ndim)
a


1


array([1, 2, 3])

In [27]:
a[0]

1

In [28]:
a[2]

3

In [29]:
b = np.array([(1,2,3), (4,5,6)])
print(b.ndim)
print(b)

2
[[1 2 3]
 [4 5 6]]


In [30]:
#[row,column]
b[0,0]

1

In [31]:
b[0,1]

2

In [32]:
b[0,2]

3

In [33]:
b[1,2]

6

In [34]:
c = np.array([[[10, 11, 12], [13, 14, 15], [16, 17, 18]],
               [[20, 21, 22], [23, 24, 25], [26, 27, 28]],
               [[30, 31, 32], [33, 34, 35], [36, 37, 38]]])
print(c.ndim)
c

3


array([[[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]],

       [[20, 21, 22],
        [23, 24, 25],
        [26, 27, 28]],

       [[30, 31, 32],
        [33, 34, 35],
        [36, 37, 38]]])

In [35]:
#c[ dim, row, col ]
c[0]

array([[10, 11, 12],
       [13, 14, 15],
       [16, 17, 18]])

In [36]:
#c[ dim, row, col ]
c[2,2,2]

38

In [37]:
#c[ dim, row, col ]
c[0,0,:3]

array([10, 11, 12])

In [38]:
#c[ dim, row, col ]
c[0,1,:2]

array([13, 14])

In [39]:
#c[ dim, row, col ]
c[1,:,:]

array([[20, 21, 22],
       [23, 24, 25],
       [26, 27, 28]])